import "./globals.css";
import Navbar from "./components/navbar";
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Portfolio in Next.js",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-gray-900`}
      >
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
